common:
 config_setting:
  1:
   id:1
   label:label_invite_group
  2:
   id:2
   label:label_accept_invite_group
  3:
   id:3
   label:label_create_thread
  4:
   id:4
   label:label_comment_thread
  5:
   id:5
   label:label_set_time
  6:
   id:6
   label:label_post_not_group
  7:
   id:7
   label:label_comment_not_group
  8:
   id:8
   label:label_post_group_owner
  9:
   id:9
   label:label_comment_group
  10:
   id:10
   label:label_set_time_read 