<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
//group
$route['group/invite_list/(:any)']		= 'group/get_invite_list';
$route['group/invite_name/(:any)']		= 'group/get_invite_name';
$route['group/(:num)/edit']				= 'group/edit';
$route['group/(:num)/confirm_edit']		= 'group/confirm_edit';
$route['group/(:num)/update']			= 'group/update';
$route['group/(:num)/delete']			= 'group/delete';
$route['group/(:num)/get_member']		= 'group/get_member/$1';
$route['group/(:num)/get_post/(:num)'] 	= 'group/get_post/$1/$2';
$route['group/post/(:num)'] 			= 'group/post/$1';
$route['group/(:num)/post/(:num)'] 		= 'group/view_post/$1/$2';
$route['group/(:num)/file/(:num)'] 		= 'group/view_file/$1/$2';
$route['group/(:num)'] 					= 'group/index/$1';
$route['group/create'] 					= 'group/create';
$route['group/confirm_create'] 			= 'group/confirm_create';
$route['group/store']					= 'group/store';
$route['group/leave']					= 'group/leave';
$route['group/get_user']				= 'group/get_user_group';
$route['group/update_user']				= 'group/update_user';
$route['group/join_group']				= 'group/join_group';
$route['group'] 						= 'group/index';
