<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$route['user'] 							= 'user/index';
$route['user/story'] 					= 'user/view_story';
$route['user/get_post/(:num)']			= 'user/get_post/$1';
$route['user/create'] 					= 'user/create_general';
$route['user/confirm_create'] 			= 'user/confirm_create_general';
$route['user/store'] 					= 'user/store_general';
$route['user/active/(:any)']			= 'user/active_user/$1';
$route['user/edit']						= 'user/edit';
$route['user/confirm_edit']				= 'user/confirm_edit';
$route['user/update']					= 'user/update';
$route['user/recommend']		 		= 'user/create_recommend';
$route['user/recommend/(:any)'] 		= 'user/create_recommend/$1';
$route['user/confirm_create_recommend'] = 'user/confirm_create_recommend';
$route['user/store_recommend']			= 'user/store_recommend';
$route['user/change_email/(:any)'] 		= 'user/change_email/$1';
$route['user/(:num)/personal_profile']	= 'user/personal_profile/$1';
$route['user/(:num)/add_blacklist_user']= 'user/add_blacklist_user/$1';
$route['user/(:num)/remove_blacklist_user'] = 'user/remove_blacklist_user/$1';
$route['user/invite'] 					= 'user/invite';
$route['user/confirm_invite']			= 'user/confirm_invite';
$route['user/send_mail_invite']			= 'user/send_mail_invite';
$route['user/send_to/(:num)']			= 'user/index/$1';
$route['user/post/(:num)']				= 'user/view_post/$1';
$route['user/file/(:num)']				= 'user/view_file/$1';