common:
 inquiry_types:
  1:
    id:1
    label:label_inq_operation
  2:
    id:2
    label:label_inq_member_regist
  4:
    id:4
    label:label_inq_login
  9:
    id:9
    label:label_inq_other