common:
 pagination:
  total_item: 3
  per_page_list:
   - 10
   - 20
   - 50
 language:
  english:
   id:english
   label:label_language_en
  japanese:
    id:japanese
    label:label_language_jp
 profile:
  gender_types:
      1:
        id:1
        label:label_gender_male
      2:
        id:2
        label:label_gender_female
 activity:
  post_types:
      1:
        id:1
        label:label_activity_post_thread
      2:
        id:2
        label:label_activity_post_comment
  flag_delete:
      1:
        id:1
        label:label_activity_post_enable
      2:
        id:2
        label:label_activity_post_delete
  expired_type:
      '-1':
        id:-1
        label:label_expired_no_limit
      0:
        id:0
        label:label_expired_designation
      3:
        id:3
        label:label_expired_72h
      365:
        id:365
        label:label_expired_1year
  file_types:
      1:
        id:1
        label:label_file_upload
      2:
        id:2
        label:label_file_unzip
 files:
  expired_types:
      1:
        id:-1
        label:label_upload_expired_type_indefined
      2:
        id:0
        label:label_upload_expired_type_specify
      3:
        id:3
        label:label_upload_expired_type_72_hours
      4:
        id:365
        label:label_upload_expire_type_a_year
  file_types:
      1:
        id:1
        label:label_upload_file_type_upload
      2:
        id:2
        label:label_upload_file_type_unzip