post/create:
 - field: post_body
   label: label_post_body
   rules: trim|required|xss_clean
comment/create:
 - field: comment_body[]
   label: label_post_body
   rules: trim|required|xss_clean
comment/update:
 - field: hdn_body[]
   label: label_post_body
   rules: trim|required|xss_clean