common:
 status_types:
  1:
    id:1
    label:label_enable
  2:
    id:2
    label:label_disable
 auth_method:
  auth_image:
    id:1
    label:label_auth_image_confirm
  auth_info:
    id:2
    label:label_auth_phone
 registered_type:
  admin:
    id:1
    label:label_registered_type_admin
  recommend:
    id:2
    label:label_registered_type_recom
  general:
    id:3
    label:label_registered_type_general
 registered_status:
  pending:
    id:0
    label:label_registered_status_pend
  active:
    id:1
    label:label_registered_status_active
  denial:
    id:2
    label:label_registered_status_denial
  hold:
    id:3
    label:label_registered_status_hold

 profile:
  gender_types:
      1:
        id:1
        label:label_gender_male
      2:
        id:2
        label:label_gender_female

  file_types:
      1:
        id:1
        label:label_file_upload
      2:
        id:2
        label:label_file_unzip

 profile_status_types:
  1:
    id:1
    label:label_public
  2:
    id:2
    label:label_private
    
 languages:
  english:
   id:english
   label:label_language_en
  japanese:
    id:japanese
    label:label_language_jp
 config_setting:
  1:
   id:1
   label:label_invite_group
  2:
   id:2
   label:label_accept_invite_group
  3:
   id:3
   label:label_create_thread
  4:
   id:4
   label:label_comment_thread
  5:
   id:5
   label:label_set_time
  6:
   id:6
   label:label_post_not_group
  7:
   id:7
   label:label_comment_not_group
  8:
   id:8
   label:label_post_group_owner
  9:
   id:9
   label:label_comment_group
  10:
   id:10
   label:label_set_time_read 